/* 
TAREAS-> 
    TABLAS
         TASK
           NAME
           DESCRIPTION
           STATE

*/

CREATE TABLE TASK(
    ID PRIMARY KEY SERIAL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    STATE BOOLEAN
);

CREATE TABLE USER(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50),
  EMAIL VARCHAR(50) UNIQUE,
  PASSWORD VARCHAR(50)
);

CREATE TABLE TASK_STATUS(
  ID SERIAL PRIMARY KEY,
  STATUS VARCHAR(20) NOT NULL UNIQUE CHECK (STATUS IN ('Pendiente', 'En progreso', 'Finalizada','Cancelada'))
)

CREATE USER_TASK(
  ID_TASK INTEGER REFERENCES TASK(ID),
  ID_USER INTEGER REFERENCES USER(ID),
  ID_STATUS INTEGER REFERENCES TASK_STATUS(ID),
  START_DATE DATE,
  DUE_DATE DATE,
  PRIMARY KEY(ID_TASK, ID_USER)
);

